--------------------------------------------------------
--  File created - Sunday-December-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENTI
--------------------------------------------------------

  CREATE TABLE "EMMA"."AGENTI" 
   (	"ID" NUMBER(38,0), 
	"IME" VARCHAR2(64 BYTE), 
	"PREZIME" VARCHAR2(64 BYTE), 
	"TELEFON" VARCHAR2(32 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"DATUM_ZAPOSLENJA" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KLIJENTI
--------------------------------------------------------

  CREATE TABLE "EMMA"."KLIJENTI" 
   (	"ID" NUMBER(38,0), 
	"IME" VARCHAR2(64 BYTE), 
	"PREZIME" VARCHAR2(64 BYTE), 
	"JMBG" NUMBER(13,0), 
	"ADRESA" VARCHAR2(64 BYTE), 
	"TELEFON" VARCHAR2(32 BYTE), 
	"TIP_KLIJENTA" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table O_NAMA
--------------------------------------------------------

  CREATE TABLE "EMMA"."O_NAMA" 
   (	"ID" NUMBER(*,0), 
	"OPIS" VARCHAR2(160 BYTE), 
	"PIB" NUMBER(*,0), 
	"MATICNI_BROJ" NUMBER(*,0), 
	"MESTO" VARCHAR2(64 BYTE), 
	"TELEFON" VARCHAR2(32 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"DIREKTOR" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POLISE
--------------------------------------------------------

  CREATE TABLE "EMMA"."POLISE" 
   (	"ID" NUMBER(38,0), 
	"AGENT_ID" NUMBER(38,0), 
	"KLIJENT_ID" NUMBER(38,0), 
	"NOVCANO_POKRICE" VARCHAR2(64 BYTE), 
	"DATUM_VAZENJA_POLISE" VARCHAR2(64 BYTE), 
	"DATUM_KREIRANJA" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPOVI_KLIJENTA
--------------------------------------------------------

  CREATE TABLE "EMMA"."TIPOVI_KLIJENTA" 
   (	"ID" VARCHAR2(38 BYTE), 
	"NAZIV" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EMMA.AGENTI
SET DEFINE OFF;
REM INSERTING into EMMA.KLIJENTI
SET DEFINE OFF;
REM INSERTING into EMMA.O_NAMA
SET DEFINE OFF;
REM INSERTING into EMMA.POLISE
SET DEFINE OFF;
REM INSERTING into EMMA.TIPOVI_KLIJENTA
SET DEFINE OFF;
