/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package osiguravajucedrustvo;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author emma
 */
public class UnosKlijenta extends javax.swing.JFrame {
    Baza baza = new Baza();

    private int id, tip;
    private String ime, prezime, jmbg, adresa, telefon, t;
   
    public UnosKlijenta() {
        initComponents();
        
        try {
            baza.poveziSaBazom();
            String queryPol = "SELECT * FROM TIPOVI_KLIJENTA";
            ResultSet rezultat = baza.naredba1.executeQuery(queryPol);

            while (rezultat.next()) {
                cb_tip.addItem(rezultat.getString("naziv"));
            }
        } catch (Exception e) {
            System.out.println("Problem ComboBox : " + e);
        } finally {
            try {
                if (baza.naredba1 != null) {
                    baza.naredba1.close();
                }
                
                if (baza.dbConn != null) {
                    baza.dbConn.close();
                }
            } catch (SQLException sqlEx) {
                System.out.println("Greska sabazom u konstruktoru! " + sqlEx);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        tf_ime = new javax.swing.JTextField();
        tfr_br = new javax.swing.JTextField();
        tf_prezime = new javax.swing.JTextField();
        tf_telefon = new javax.swing.JTextField();
        tf_jmbg = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jPronadji10 = new javax.swing.JButton();
        jIzmeni9 = new javax.swing.JButton();
        jDodaj9 = new javax.swing.JButton();
        jObrisi9 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        tf_adresa = new javax.swing.JTextField();
        cb_tip = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel65.setText("Redni broj:");

        jLabel66.setText("Ime:");

        jLabel67.setText("Prezime:");

        jLabel68.setText("Telefon:");

        jLabel69.setText("Adresa:");

        jLabel70.setText("Tip klijenta:");

        jPronadji10.setText("Pronadji");
        jPronadji10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPronadji1ActionPerformed(evt);
            }
        });

        jIzmeni9.setText("Izmeni");
        jIzmeni9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIzmeniActionPerformed(evt);
            }
        });

        jDodaj9.setText("Dodaj");
        jDodaj9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajActionPerformed(evt);
            }
        });

        jObrisi9.setText("Obrisi");
        jObrisi9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jObrisiActionPerformed(evt);
            }
        });

        jLabel71.setText("JMBG:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPronadji10)
                        .addGap(18, 18, 18)
                        .addComponent(jIzmeni9)
                        .addGap(18, 18, 18)
                        .addComponent(jDodaj9)
                        .addGap(18, 18, 18)
                        .addComponent(jObrisi9))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel70)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel66)
                                    .addGap(231, 231, 231)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_prezime, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_ime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(tf_jmbg, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel69)
                                        .addComponent(jLabel68))
                                    .addGap(202, 202, 202)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_adresa, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_telefon, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cb_tip, javax.swing.GroupLayout.Alignment.TRAILING, 0, 177, Short.MAX_VALUE)))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel67)
                                        .addComponent(jLabel71))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel65)
                                    .addGap(186, 186, 186)
                                    .addComponent(tfr_br))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel65)
                    .addComponent(tfr_br, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(tf_ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addComponent(tf_prezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(tf_jmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(tf_adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addComponent(cb_tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPronadji10)
                    .addComponent(jIzmeni9)
                    .addComponent(jObrisi9)
                    .addComponent(jDodaj9))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Unos klijenta");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/osiguravajucedrustvo/Slike/klijenti1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jObrisiActionPerformed
        System.out.println("Dugme obrisi pritisnuto!");

        if (tfr_br.getText().isEmpty()) {
            System.out.println("Molim Vas, unesite id.");
        } else {
            izbrisiIzBaze();
        }
    }

    private void izbrisiIzBaze() {
        try {
            baza.poveziSaBazom();
            id = Integer.parseInt(tfr_br.getText());

            String izbrisiQuery = "DELETE FROM KLIJENTI WHERE ID = " + id;
            System.out.println(izbrisiQuery);
            baza.naredba1.executeUpdate(izbrisiQuery);

        } catch (Exception e) {
            System.out.println("Greska prilikom brisanja!" + e.getMessage());
        } finally {
            try {
                if (baza.naredba1 != null) {
                    baza.naredba1.close();
                }
                
                if (baza.dbConn != null) {
                    baza.dbConn.close();
                }
            } catch (SQLException sqlEx) {
                System.out.println("Greska prilikom zatvaranja baze! " + sqlEx.getMessage());
            }
        }
    }//GEN-LAST:event_jObrisiActionPerformed

    private void jDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajActionPerformed
        System.out.println("Dugme dodaj pritisnuto.");

        if (tfr_br.getText().equals("")) {
            System.out.println("Molim Vas, unesite nesto.");
        } else {
            dodajUBazu();
        }
    }//GEN-LAST:event_jDodajActionPerformed

    private void jIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIzmeniActionPerformed
        System.out.println("Dugme izmeni pritisnuto.");

        if (tfr_br.getText().isEmpty()) {
            System.out.println("Molim Vas unesite mesto.");
        } else {
            azuriratiBazu();
        }
    }//GEN-LAST:event_jIzmeniActionPerformed

    private void jPronadji1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPronadji1ActionPerformed
        System.out.println("Dugme pronadji pritisnuto");

        if (tfr_br.getText().isEmpty()) {
            System.out.println("Molimo Vas unesite broj");
        } else {
            System.out.println("Redni broj: = " + tfr_br.getText());
            this.id = Integer.parseInt(tfr_br.getText());
            pronadjiUBazi();
            tf_ime.setText(ime);
            tf_prezime.setText(prezime);
            tf_jmbg.setText(jmbg);
            tf_adresa.setText(adresa);
            tf_telefon.setText(telefon);
            cb_tip.setSelectedItem(tip);
        }
    }//GEN-LAST:event_jPronadji1ActionPerformed

    private void dodajUBazu() {
        try {
            baza.poveziSaBazom();

            id = Integer.parseInt(tfr_br.getText());
            ime = tf_ime.getText().replace("'", "");
            prezime = tf_prezime.getText().replace("'", "");
            jmbg = tf_jmbg.getText().replace("'", "");
            adresa = tf_adresa.getText().replace("'", "");
            telefon = tf_telefon.getText().replace("'", "");
            tip = cb_tip.getSelectedIndex() + 1;
            
            String proveriQuery = "SELECT * FROM KLIJENTI WHERE ID = " + id;
            ResultSet r = baza.naredba1.executeQuery(proveriQuery);
            
            if (!r.next()) {
                String dodajQuery = "INSERT INTO KLIJENTI (id, ime, prezime, jmbg, adresa, telefon, tip_klijenta)VALUES('" + id + "','" + ime + "','" + prezime + "','" + jmbg + "','" + adresa + "','" + telefon + "','" + tip + "')";
                System.out.println(dodajQuery);
                baza.naredba1.executeUpdate(dodajQuery);
            } else {
                System.out.println("Vec postoji taj redni broj!");
            }
        } catch (Exception e) {
            System.out.println("Neuspesno dodavanje u bazu!" + e.getMessage());
        } finally {
            try {
                if (baza.naredba1 != null) {
                    baza.naredba1.close();
                }
                
                if (baza.dbConn != null) {
                    baza.dbConn.close();
                }
            } catch (SQLException sqlEx) {
                System.out.println("Greska prilikom zatvaranja baze! " + sqlEx.getMessage());
            }
        }
    }
    
    private void azuriratiBazu() {
        try {
            baza.poveziSaBazom();
            id = Integer.parseInt(tfr_br.getText());
            ime = tf_ime.getText().replace("'", "");
            prezime = tf_prezime.getText().replace("'", "");
            jmbg = tf_jmbg.getText().replace("'", "");
            adresa = tf_adresa.getText().replace("'", "");
            telefon = tf_telefon.getText().replace("'", "");
            tip = cb_tip.getSelectedIndex() + 1;
            
            String azurirajQuery = "UPDATE KLIJENTI SET ime = '" + ime + "', prezime = '" + prezime + "', jmbg = '" + jmbg + "', adresa = '" + adresa + "', telefon = '" + telefon + "',"
                    + "tip_klijenta = '" + tip + "' WHERE ID = " + id + "";
            baza.naredba1.executeUpdate(azurirajQuery);
        } catch (Exception e) {
            System.out.println("Javila se greska prilikom izmene: " + e.getMessage());
        } finally {
            try {
                if (baza.naredba1 != null) {
                    baza.naredba1.close();
                }
                
                if (baza.dbConn != null) {
                    baza.dbConn.close();
                }
            } catch (SQLException sqlEx) {
                System.out.println("SQLIzuzetak za vreme close(): " + sqlEx.getMessage());
            }
        }
    }
    
    private void pronadjiUBazi() {
        try {
            baza.poveziSaBazom();
            id = Integer.parseInt(tfr_br.getText());
           
            String naredbaSQL = "SELECT * FROM KLIJENTI WHERE ID = " + id;

            ResultSet rezultat = baza.naredba1.executeQuery(naredbaSQL);
            
            while (rezultat.next()) {
                ime = rezultat.getString("ime");
                prezime = rezultat.getString("prezime");
                jmbg = rezultat.getString("jmbg");
                adresa = rezultat.getString("adresa");
                telefon = rezultat.getString("telefon");
            }
            
            String naredbaSQL2 = "SELECT t.id, t.naziv FROM TIPOVI_KLIJENTA t, KLIJENTI k WHERE k.tip_klijenta = t.id AND k.id = " + id;
            ResultSet r = baza.naredba1.executeQuery(naredbaSQL2);
            
            while (r.next()) {
                t = r.getString("naziv");
                System.out.println(t);
            }
        } catch (Exception e) {
            System.out.println("Izuzeztak izbacen: " + e.getMessage());
        } finally {
            try {
                if (baza.naredba1 != null) {
                    baza.naredba1.close();
                }
                
                if (baza.dbConn != null) {
                    baza.dbConn.close();
                }
            } catch (SQLException sqle) {
                System.out.println("SQLIzuzetak za vreme close(): "
                        + sqle.getMessage());
            }
        }
    }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosKlijenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_tip;
    private javax.swing.JButton jDodaj9;
    private javax.swing.JButton jIzmeni9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JButton jObrisi9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JButton jPronadji10;
    private javax.swing.JTextField tf_adresa;
    private javax.swing.JTextField tf_ime;
    private javax.swing.JTextField tf_jmbg;
    private javax.swing.JTextField tf_prezime;
    private javax.swing.JTextField tf_telefon;
    private javax.swing.JTextField tfr_br;
    // End of variables declaration//GEN-END:variables
}
